### ISSUE TITLE
type 'Null' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by chentianxin** [leanflutter/flutter_distributor#10]
运行 ```flutter_distributor package --platform=mac --targets=dmg,zip``` 后异常

```shell
type 'Null' is not a subtype of type 'List<dynamic>' in type cast
#0      new DistributeOptions.fromJson (package:flutter_distributor/src/distribute_options.dart:23:48)
#1      FlutterDistributor.distributeOptions (package:flutter_distributor/src/flutter_distributor.dart:63:48)
#2      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:133:35)
#3      CommandPackage.run (file:///Users/mac/.pub-cache/hosted/pub.flutter-io.cn/flutter_distributor-0.0.9/bin/command_package.dart:39:23)
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#5      main (file:///Users/mac/.pub-cache/hosted/pub.flutter-io.cn/flutter_distributor-0.0.9/bin/main.dart:28:16)
<asynchronous suspension>
```
/// distribute_options.yaml
```yaml
output: dist/
```
/// flutter_distributor 0.0.9.

**Comment by yy1300326388** [comment]
It is recommended to improve your distribute_options.yaml
https://distributor.leanflutter.org/#full-example-configuration

**Comment by chentianxin** [comment]
![F7ACB770-EA9B-4D8B-A85B-7E907A68B477](https://user-images.githubusercontent.com/49486355/147431672-39eaf3c0-0d76-4006-a3dc-fb22f85effd3.png)

**Comment by lijy91** [comment]
后续将进行改进，如果需要打包 dmg，目前需要参考 hello_world 示例添加 macos/packaging/dmg/ 目录及对下面的make_config.yaml 文件进行修改。

> 另外 --platform=mac 应该改为 --platform=macos

**Comment by lijy91** [comment]
build_args 如果你在使用 flutter build macos 参数时无相关参数，请将不使用的参数移除，如 flavor, target-platfrom

**Comment by lijy91** [comment]
已修复，请更新到 v0.1.0
