### ISSUE TITLE
AppImage Build process is failing

### ISSUE THREAD

**Issue by aandrew-me** [leanflutter/flutter_distributor#103]
The appimage build process fails on a Linux Distro which is not Debian based (a.k.a it doesn't use apt as package manager).
I noticed that the build script is trying to do something with `apt-get`. 

In this case it would be good if you specify in the docs that a debian based Linux distro is needed to build appimages.

**Comment by KRTirtho** [comment]
Currently according to [appimage-builder Docs](https://appimage-builder.readthedocs.io/en/latest/faq.html#what-systems-are-supported) (which is used under the hood) AppImages can only be built in **Debian, Ubuntu and Arch based distros**. So if you're on anything other than that you're out of luck although you can always use podman/docker containers

Also, there're some appimage-builder installation instructions in the [`flutter_distributor`](https://distributor.leanflutter.org/docs/makers/appimage) docs but I'd recommend you to follow the [Official Docs of AppImage Builder](https://appimage-builder.readthedocs.io/en/latest/intro/install.html) to install proper dependencies required for it
