### ISSUE TITLE
PathNotFoundException: Cannot open file, path = 'windows/packaging/exe/make_config.yaml'

### ISSUE THREAD

**Issue by novas1r1** [leanflutter/flutter_distributor#104]
Hello,
when I'm trying to run `flutter_distributor release --name dev --jobs release-windows` with GitHub actions, I get the following error:

```
Building Windows application...                                 
Successfully built Directory: 'build/windows/runner/Release' in 204s
PathNotFoundException: Cannot open file, path = 'windows/packaging/exe/make_config.yaml' (OS Error: The system cannot find the path specified.
, errno = 3)
```

Any tips?

**Comment by cybrox** [comment]
Have you tried running it locally and does it work there?

It looks like `windows/packaging/exe/make_config.yaml` does not exist. Have you checked that it is present in the CI build? (See [this par of the docs](https://distributor.leanflutter.org/docs/makers/exe))

**Comment by lijy91** [comment]
> Have you tried running it locally and does it work there?
> 
> It looks like `windows/packaging/exe/make_config.yaml` does not exist. Have you checked that it is present in the CI build? (See [this part of the docs](https://distributor.leanflutter.org/docs/makers/exe))

Yes, it looks like this file is missing
