### ISSUE TITLE
低版本使用

### ISSUE THREAD

**Issue by 18805699674** [leanflutter/flutter_distributor#11]
ERR : The current Dart SDK version is 2.13.3.
    | 
    | Because flutter_distributor >=0.0.6 depends on pubspec_parse >=1.2.0 which requires SDK version >=2.14.0 <3.0.0, flutter_distributor >=0.0.6 is forbidden.
    | So, because pub global activate depends on flutter_distributor 0.0.9, version solving failed.

低版本现在不可以用吗？

**Comment by lijy91** [comment]
看一下是 pubspec_parse 最新版本（1.2.0）要求 dart >= 2.14.0，下个版本将 降级到 1.1.0

**Comment by lijy91** [comment]
已修复，请更新到 v0.1.0
