### ISSUE TITLE
IOS打包出来的IPA文件是上个版本的

### ISSUE THREAD

**Issue by jethroHuang** [leanflutter/flutter_distributor#12]
修改了版本号（1.0.7 -> 1.0.8）以及完善了一些APP的功能，然后调用 flutter_distributor 打包上传到蒲公英，发现 IOS 的 IPA 包版本竟然是 1.0.7，功能也是 1.0.7 的，Android又没问题。用手动的方式调用flutter build ios 然后xcode打包 ipa 出来的版本则是最新的

**Comment by jethroHuang** [comment]
Packaging student 1.0.8+4 as ipa:
Building...
Archiving com.viplangrun.xxxx...
Automatically signing iOS for device deployment using specified development team in Xcode project: B28RV5xxxxx
Running pod install...
3.1s

Running Xcode build...

Xcode archive done.                                         103.4s
Built /Users/jethro/Documents/vip/zhs-app/build/ios/archive/Runner.xcarchive.

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Building IPA...
13.3s
Built IPA to /Users/jethro/Documents/vip/zhs-app/build/ios/ipa.
Successfully builded Directory: 'build/ios/ipa'
Successfully packaged dist/1.0.8+4/student-1.0.8+4-ios.ipa
Publishing to pgyer : ██████████████████████████████████████████████████████████ 28130158/28130158 100.0% 8979798833%  
Successfully published http://www.pgyer.com/4f9d224bede8e59a1964323c49590c8d

日志补充

sflutter_distributor: 0.1.1
flutter: Flutter 2.5.3
xcode: 13.2.1 (13C100)

**Comment by yy1300326388** [comment]
可以先 `flutter clean` ，后期版本会加上自动  `clean`

**Comment by lijy91** [comment]
已在编译前增加清理步骤，将在下一版本发布
