### ISSUE TITLE
PathNotFoundException

### ISSUE THREAD

**Issue by Bullets-jyr** [leanflutter/flutter_distributor#125]
[Error Log]

PathNotFoundException: Cannot open file, path = 'windows/packaging/exe/make_config.yaml' (OS Error: 지정된 경로를 찾을 수 없습니다.
, errno = 3)

RELEASE FAILED in 87s
PathNotFoundException: Cannot open file, path = 'windows/packaging/exe/make_config.yaml' (OS Error: 지정된 경로를 찾을 수 없습니다.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:533:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:578:18)
#4      loadMakeConfigYaml (package:app_package_maker/src/app_package_maker.dart:10:39)
#5      MakeExeConfigLoader.load (package:flutter_app_packager/src/makers/exe/make_exe_config.dart:107:17)
#6      FlutterAppPackager.package (package:flutter_app_packager/src/flutter_app_packager.dart:34:39)
#7      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:181:51)
<asynchronous suspension>
#8      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:320:45)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

How can I resolve that PathNotFoundException?

Does adding make_config.yaml as below solve the problem?
Then I wonder what app_id is and how I can create it.

https://distributor.leanflutter.org/docs/makers/exe
Add make_config.yaml to your project windows/packaging/exe directory.
The value of AppId uniquely identifies this application.
Do not use the same AppId value in installers for other applications.
app_id: 5B599538-42B1-4826-A479-AF079F21A65D
publisher: LeanFlutter
publisher_url: https://github.com/leanflutter/flutter_distributor
display_name: Hello 世界
create_desktop_icon: true
install_dir_name: HELLO-WORLD
locales:
  - en
  - zh

If you proceed by adding make_config.yaml, the following error occurs. How can i solve this?

[Error Log]

Disk spanning must be enabled in order to create an installation larger than 2100000000 bytes in size.
Compile aborted.
MakeError
#0      AppPackageMakerExe._make (package:flutter_app_packager/src/makers/exe/app_package_maker_exe.dart:49:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:181:35)
<asynchronous suspension>
#2      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:320:45)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

RELEASE FAILED in 466s
MakeError
#0      AppPackageMakerExe._make (package:flutter_app_packager/src/makers/exe/app_package_maker_exe.dart:49:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:181:35)
<asynchronous suspension>
#2      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:320:45)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

**Comment by lijy91** [comment]
Please create windows/packaging/exe/make_ Config.yaml file
https://distributor.leanflutter.org/docs/makers/exe
