### ISSUE TITLE
字符集错误，具体哪里原因不详

### ISSUE THREAD

**Issue by cpsoft** [leanflutter/flutter_distributor#131]
Unhandled exception:
FormatException: Missing extension byte (at offset 229)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      DefaultShellExecutor.exec.<anonymous closure> (package:flutter_distributor/src/utils/default_shell_executor.dart:35:33)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#7      _StreamController._add (dart:async/stream_controller.dart:650:7)
#8      _StreamController.add (dart:async/stream_controller.dart:598:5)
#9      _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#14     _StreamController._add (dart:async/stream_controller.dart:650:7)
#15     _StreamController.add (dart:async/stream_controller.dart:598:5)
#16     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899:33)
#17     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356:14)

**Comment by cpsoft** [comment]
Parsing [Languages] section, line 27
   Reading file: C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl

默认安装Inno Setup 6时没有中文语言文件。加上后可以执行过。建议处理一下提示，能友好一点。

**Comment by yang-dong-dong** [comment]
https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl

**Comment by huangsir0** [comment]
哥们解决了吗，我也遇到这个问题

**Comment by lijy91** [comment]
我找到这个问题发生的原因，因为防病毒软件的实时防护导致了 ISCC.exe 在执行失败时输出了文件被其他程序打开的中文消息（目前还没处理非 utf8 的消息导致），解决办法是关闭实时防护或将相应的目录添加到白名单中 https://stackoverflow.com/a/20123804/4049871
