### ISSUE TITLE
Support github release publisher

### ISSUE THREAD

**Issue by lijy91** [leanflutter/flutter_distributor#14]

**Comment by yy1300326388** [comment]
### Docs
- https://docs.github.com/cn/enterprise-server@3.2/rest/reference/releases#get-the-latest-release
- https://github.com/skx/github-action-publish-binaries

**Comment by lijy91** [comment]
可直接使用 https://pub.dev/packages/github

**Comment by yy1300326388** [comment]
发现一个需求点，多个文件上传后，结果比较分散，需要一个最终的结果输出，类似下面的表格

|File|Download url|
|--|--|
|hello_world-1.0.0.1-android.aab|https://github.com/yy1300326388/flutter_distributor/releases/download/v0.1.2/hello_world-1.0.0.1-android.aab|
|hello_world-1.0.0.1-android.apk|https://github.com/yy1300326388/flutter_distributor/releases/download/v0.1.2/hello_world-1.0.0.1-android.apk|
|hello_world-1.0.0.1-web.zip|https://github.com/yy1300326388/flutter_distributor/releases/download/v0.1.2/hello_world-1.0.0.1-web.zip|

**Comment by yy1300326388** [comment]
> 可直接使用 https://pub.dev/packages/github

用他这个没有进度，可以使用部分接口，上传自己写

**Comment by yy1300326388** [comment]
讨论结果
--- 
1. 如果 release-title 不存在，则创建草稿 release
2. 如果 release-title 已存在，则不创建
3. 上传资源文件

**Comment by yy1300326388** [comment]
- 记录
![image](https://user-images.githubusercontent.com/8764899/150509682-54588ab7-7681-4f29-a48b-02ff210b1344.png)

**Comment by lijy91** [comment]
已合并 #32 ，将在下一版本中发布
