### ISSUE TITLE
如何配置Release路径？Directory listing failed, path = 'build/windows/runner/Release\*'

### ISSUE THREAD

**Issue by lingsifeng** [leanflutter/flutter_distributor#145]
如何配置Release路径？打包后如图多了一个x64层级，导致Directory listing failed, path = 'build/windows/runner/Release\*'
![image](https://github.com/leanflutter/flutter_distributor/assets/18637610/00876f9c-d5fd-4564-8b97-01467a6078e5)

**Comment by karniv00l** [comment]
Same here

**Comment by thitlwincoder** [comment]
same here

**Comment by yuhaya** [comment]
same

**Comment by KRTirtho** [comment]
Failing CI https://github.com/KRTirtho/spotube/actions/runs/6959755755/job/18938537478 :(
