### ISSUE TITLE
When building the .exe package, how to configure codesign?

### ISSUE THREAD

**Issue by zmhu** [leanflutter/flutter_distributor#152]
I did not find any information about configuring codesign when packaging the exe file in the document. If this feature is not available, can it be added?

**Comment by cybrox** [comment]
`flutter_distributor` uses InnoSetup for creating `.exe` packages. So you can follow [their documentation](https://jrsoftware.org/ishelp/index.php?topic=setup_signtool) for configuring signing.

See [this part of the docs](https://distributor.leanflutter.dev/makers/exe/) on how to provide a custom Inno Setup config.

**Comment by lijy91** [comment]
> provide

that's right
