### ISSUE TITLE
我想请问一下  exe  程序快捷应用名怎么修改？

### ISSUE THREAD

**Issue by huangsir0** [leanflutter/flutter_distributor#176]
![image](https://github.com/leanflutter/flutter_distributor/assets/47199570/0cd5edf5-edef-4e40-9fcb-3dfd4bd98cba)

**Comment by lijy91** [comment]
配置一下 make_config.yaml 里的 display_name 即可。

**Comment by huangsir0** [comment]
![image](https://github.com/leanflutter/flutter_distributor/assets/47199570/a24b586e-2c9e-41de-b7df-3faec4a6c9d0)

我配置了，但不知道为什么不生效

**Comment by huangsir0** [comment]
谢谢大佬，已经解决了。3Q
