### ISSUE TITLE
Please upgrade uuid to v4

### ISSUE THREAD

**Issue by kjxbyz** [leanflutter/flutter_distributor#178]
```
Because flutter_distributor >=0.4.0 depends on flutter_app_publisher ^0.4.0 which depends on qiniu_sdk_base ^0.5.0, flutter_distributor >=0.4.0 requires qiniu_sdk_base ^0.5.0.
And because qiniu_sdk_base >=0.4.0 depends on uuid ^3.0.5, flutter_distributor >=0.4.0 requires uuid ^3.0.5.
So, because picguard depends on both uuid ^4.4.0 and flutter_distributor ^0.4.0, version solving failed.
```

**Comment by maxfornacon** [comment]
Did you add `flutter_distributor` to your `pubspec.yaml`? 

Try removing it and use `dart pub global activate flutter_distributor`. 


I use uuid ^4.4.0 in my project and it works totally fine.

**Comment by kjxbyz** [comment]
```
# pubspec.yaml
dependency_overrides:
  uuid: ^4.4.0
```

**Comment by lijy91** [comment]
> Did you add `flutter_distributor` to your `pubspec.yaml`?
> 
> Try removing it and use `dart pub global activate flutter_distributor`.
> 
> I use uuid ^4.4.0 in my project and it works totally fine.

That's right, don't add it to your project dependencies

**Comment by kjxbyz** [comment]
The key to the problem is not whether it is a global installation, but a version conflict. Global installation also has problems.
