### ISSUE TITLE
Support qiniu publisher

### ISSUE THREAD

**Issue by lijy91** [leanflutter/flutter_distributor#19]

**Comment by yy1300326388** [comment]
这个我可以添加支持上，需要看一下 api

**Comment by yy1300326388** [comment]
添加了七牛存储，是不是 OSS（阿里云存储）、COS（腾讯云存储） 也要添加呢？

**Comment by lijy91** [comment]
> 添加了七牛存储，是不是 OSS（阿里云存储）、COS（腾讯云存储） 也要添加呢？

后续可以添加，不过还是优化开发 appcenter 这类国外的分发平台。

**Comment by yy1300326388** [comment]
> > 添加了七牛存储，是不是 OSS（阿里云存储）、COS（腾讯云存储） 也要添加呢？
> 
> 后续可以添加，不过还是优化开发 appcenter 这类国外的分发平台。

👍🏻 赞同，我添加了 #20 ，觉得 #13 和 #20 的优先级更高一点，单纯的存储优先级可以放到最后

**Comment by lijy91** [comment]
已支持，将在下一版本发布
