### ISSUE TITLE
请问target-platform的配置还有哪几个选项？我看你们官方的示例代码写的android-arm,android-arm64

### ISSUE THREAD

**Issue by yaochangliang159** [leanflutter/flutter_distributor#190]
target-platform的配置还有哪几个选项？我看你们官方的实例代码写的android-arm,android-arm64，是不是还应该有android-armeabi-v7a的选项呢？因为我们项目配置的是:
ndk {
            abiFilters 'armeabi-v7a','arm64-v8a'
        }
这两个选项应该怎么在target-platform里面写呢

**Comment by lijy91** [comment]
build_args 下的所有字段均为 flutter build 的参数，请执行 `flutter build apk --help` 命令查看 target-platform 所支持的值。

```
    --target-platform                                        The target platform for which the app is compiled.
                                                             [android-arm (default), android-arm64 (default), android-x86, android-x64 (default)]

```
