### ISSUE TITLE
Upgrade dependent library

### ISSUE THREAD

**Issue by Er-Dong-Chen** [leanflutter/flutter_distributor#192]

**Comment by Er-Dong-Chen** [comment]
Whether the version of http that the project depends on can be upgraded to 1.0

**Comment by lijy91** [comment]
flutter_distributor is a global tool, so the http version does not matter.

**Comment by Er-Dong-Chen** [comment]
But it relies on other third-party libraries, which rely on http libraries that are too old for three years

**Comment by Er-Dong-Chen** [comment]
When there are other libraries that also rely on http conflict, it is already their own script packaging published
