### ISSUE TITLE
I encountered this when executing the packaging command. How to solve it? ERROR_ACCESS_DENIED file system exception thrown while trying to create a symlink from source to dest

### ISSUE THREAD

**Issue by msnnyusos** [leanflutter/flutter_distributor#194]
ERROR_ACCESS_DENIED file system exception thrown while trying to create a symlink from source to dest
BuildError: Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
ERROR_ACCESS_DENIED file system exception thrown while trying to create a symlink from source to dest

#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:152:27)
<asynchronous suspension>
#2      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:329:45)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

**Comment by lijy91** [comment]
看起来和与这个有关 https://github.com/flutter/flutter/issues/120196
