### ISSUE TITLE
windows install flutter_distributor failed? 

### ISSUE THREAD

**Issue by Aaron0525** [leanflutter/flutter_distributor#199]
use 'dart pub global activate flutter_distributor' install，but  remind me  "Failed to decode data using encoding 'utf-8'"，why?
![flutter_distributpr](https://github.com/leanflutter/flutter_distributor/assets/25900981/47717b13-f617-4858-97f6-348ba65014aa)

**Comment by lijy91** [comment]
If you are using `PowerShell`, add the `.bat` suffix.

**Comment by crablet** [comment]
same here
-----------------------
username in ~ λ dart pub global deactivate flutter_distributor
Failed to decode data using encoding 'utf-8', path = 'C:\Users\username\AppData\Local\Pub\Cache\bin\protoc.exe'

And the given command by @lijy91 does not work.

**Comment by crablet** [comment]
same here

error message:
username in ~ λ dart pub global deactivate flutter_distributor
Failed to decode data using encoding 'utf-8', path = 'C:\Users\username\AppData\Local\Pub\Cache\bin\protoc.exe'

And the given command by @lijy91 does not work for me.
