### ISSUE TITLE
Support Firebase publisher

### ISSUE THREAD

**Issue by yy1300326388** [leanflutter/flutter_distributor#20]

**Comment by yy1300326388** [comment]
docs ：

- iOS ：https://firebase.google.com/docs/app-distribution/ios/distribute-cli
- Android ：https://firebase.google.com/docs/app-distribution/android/distribute-cli
- Github Action Demo：https://github.com/wzieba/Firebase-Distribution-Github-Action/blob/master/entrypoint.sh

**Comment by lijy91** [comment]
已合并 #23
