### ISSUE TITLE
Unhandled exception: type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by zx0450** [leanflutter/flutter_distributor#200]
zaakman@ZaakMandeMBP-2 project-name % flutter_distributor release --name dev
Unhandled exception:
type 'String' is not a subtype of type 'int' of 'index'
#0      PubDevApi.getLatestVersionFromPackage (package:flutter_distributor/src/utils/pub_dev_api.dart:15:27)
<asynchronous suspension>
#1      FlutterDistributor.checkVersion (package:flutter_distributor/src/flutter_distributor.dart:102:9)
<asynchronous suspension>
#2      main (file:///Users/zaakman/.pub-cache/hosted/mirrors.cloud.tencent.com%2547dart-pub%2547/flutter_distributor-0.4.4/bin/main.dart:44:5)
<asynchronous suspension>

**Comment by lijy91** [comment]
已对腾讯源做了兼容，但建议使用官方 pub.dev 源。
