### ISSUE TITLE
The minimum Dart version supported by `flutter_distributor` is 3.4.0

### ISSUE THREAD

**Issue by kjxbyz** [leanflutter/flutter_distributor#205]
1. Can the minimum version requirement of dart be lowered?
2. Can `flutter_app_packager` also be used as a command line tool, or can a command line tool package named `flutter_packager` be added, which is only used for packaging?

```
Resolving dependencies...
The current Dart SDK version is 3.3.4.

Because every version of flutter_distributor from git depends on flutter_app_publisher ^0.4.5 which depends on googleapis ^13.2.0, every version of flutter_distributor from git requires googleapis ^13.2.0.
So, because googleapis >=13.2.0 requires SDK version ^3.4.0 and pub global activate depends on flutter_distributor from git, version solving failed.
```

**Comment by lijy91** [comment]
1. Please install flutter_distributor globally
2. I won’t do that

**Comment by kjxbyz** [comment]
1. This has nothing to do with global installation. It will install the highest version compatible with the local flutter version (which corresponds to a dart version by default), which is not necessarily the latest version of the package.
