### ISSUE TITLE
The generated RPM package does not install correctly

### ISSUE THREAD

**Issue by KMACEL** [leanflutter/flutter_distributor#209]
I am developing an application in Flutter. I packaged it as rpm. But when I install it on the device, the application is installed to "/usr/share/{{MY_PACKAGE_NAME}}/{{MY_APP_NAME}}". Then it tries to make a symbolic link from /usr/share/{{MY_PACKAGE_NAME}}/{{MY_PACKAGE_NAME}} under /usr/bin/. In other words, it makes the wrong path a symbolic link. What should I do?

Installed Location : 
/usr/share/{{MY_PACKAGE_NAME}}/{{MY_APP_NAME}}

symbolic Link
/usr/bin/{{MY_PACKAGE_NAME}} -> /usr/share/{{MY_PACKAGE_NAME}}/{{MY_PACKAGE_NAME}}

The process that needs to happen is this
/usr/bin/{{MY_APP_NAME}} -> /usr/share/{{MY_PACKAGE_NAME}}/{{MY_APP_NAME}}

**Comment by canxin121** [comment]
Same problem, this also causes the gnome desktop to fail to show the application shortcut

**Comment by canxin121** [comment]
``` bash
dart pub global activate --source git https://github.com/canxin121/flutter_distributor --git-ref temp --git-path packages/flutter_distributor
```

rpm/make_config.yaml
```
bin_name:  'The right executable bin name'
```
