### ISSUE TITLE
publish_to fir. android release failed

### ISSUE THREAD

**Issue by jackson0122** [leanflutter/flutter_distributor#230]
Successfully packaged build/1.0.0+1/abc-1.0.0+1-android.apk

RELEASE FAILED in 47s
Exception: Missing `ANDROID_HOME` environment variable.
#0      AppPackageParserApk.parse (package:parse_app_package/src/parsers/apk/app_package_parser_apk.dart:14:7)
#1      parseAppPackage (package:parse_app_package/src/parse_app_package.dart:15:17)
#2      AppPackagePublisherFir.publish (package:flutter_app_publisher/src/publishers/fir/app_package_publisher_fir.dart:68:37)
#3      FlutterAppPublisher.publish (package:flutter_app_publisher/src/flutter_app_publisher.dart:30:28)
#4      FlutterDistributor.publish (package:flutter_distributor/src/flutter_distributor.dart:251:56)
#5      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:345:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

 - name: dev-android
        package:
          platform: android
          target: apk
          skip_clean: true	
          build_args:
            target-platform: android-arm64
        publish_to: fir

ios is right

**Comment by jackson0122** [comment]
publish_to pgyer is right

**Comment by jackson0122** [comment]
variables:
  FIR_API_TOKEN: "sdasnjsadhsakdashjkdgaskhjgd"
output: build/
releases:
  - name: dev
    jobs:
      - name: dev-android
        package:
          platform: android
          target: apk
          skip_clean: true	
          build_args:
            target-platform: android-arm64
        publish_to: fir
      - name: dev-ios
        package:
          platform: ios
          target: ipa
          skip_clean: true	
          build_args:
            export-method: development
        publish_to: fir

**Comment by lijy91** [comment]
需要在环境变量里配置你的 ANDROID_HOME
