### ISSUE TITLE
dart: not found (line number 8 in one of distributor's file)    main.dart  snapshot not found;     bin/sh: 1: flutter: not found

### ISSUE THREAD

**Issue by iatndiag** [leanflutter/flutter_distributor#237]
You wrote a comment after line 8, but i don't understand it. Should i manually copy all dart sdk into your folder? Could you help with your installation manual, is it complete manual? 

I installed Studio 64 on Win and Ubuntu, wrote more than 7k lines of dart code. Build my proj. for Win, Android, Mac and Linux.

But ... now i don't know what should i do with this error

Could you send .bashrc and folder from your computer? Please, could you send all the folder from you computer? Or give please non-misleading answer?

**Comment by iatndiag** [comment]
![almost solved](https://github.com/user-attachments/assets/7e7af5ce-4722-422a-a626-5efebc35d6d8)

**Comment by iatndiag** [comment]
![Uploading worked.png…]()

**Comment by iatndiag** [comment]
It cannot run from your file !!!
But can run from command from your file!!!

**Comment by iatndiag** [comment]
![errors](https://github.com/user-attachments/assets/5bc5de41-ee6e-4a50-a838-06822e5bb765)

release

**Comment by cybrox** [comment]
This is not an issue with `flutter_distributor` but an issue with the `PATH` setup on your local machine.

Please refer to [a guide](https://www.baeldung.com/linux/path-variable) on how to properly set up your `PATH`.

For working with Flutter, the directory containing the `flutter` executable needs to be in your `$PATH`. For working with global flutter libraries such as `flutter_distributor`, [the global pub directory needs to be in your `$PATH` too](https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path).
