### ISSUE TITLE
ios打包出错

### ISSUE THREAD

**Issue by gp242009** [leanflutter/flutter_distributor#33]
![截屏2022-01-21 下午5 29 17](https://user-images.githubusercontent.com/18589869/150504127-18fd53a0-2cc2-4342-a0d1-d446117435ba.png)

**Comment by lijy91** [comment]
这看起来打包的是 Android

**Comment by lijy91** [comment]
首次使用前可以先执行 flutter build apk 或者 flutter build ipa 先确定两个命令可以正确执行

**Comment by gp242009** [comment]
自己环境没配好，已解决。
