### ISSUE TITLE
[windows]release报错，可以打包，无法上传

### ISSUE THREAD

**Issue by yhsj0919** [leanflutter/flutter_distributor#44]
![image](https://user-images.githubusercontent.com/7219412/157838615-1f566fa3-ff4f-4468-b7b8-276fc75c3eaa.png)
![image](https://user-images.githubusercontent.com/7219412/157838737-4c18e160-b3d4-4cca-8bb3-be740596048b.png)

**Comment by lijy91** [comment]
1. 是否已添加 packaging/exe 等配置文件？
2. 单独使用 package 命令测试一下单独编译是否可以成功

**Comment by yhsj0919** [comment]
有配置文件
直接运行这个命令 flutter_distributor package --platform=windows --targets=exe
可以出包，但是也会一样的报错
![image](https://user-images.githubusercontent.com/7219412/157843179-69dbe414-61ff-42f3-b4d7-214efaec3e3c.png)

**Comment by yhsj0919** [comment]
清理了一下环境，重新安装后正常了
