### ISSUE TITLE
Support AppStore publisher

### ISSUE THREAD

**Issue by yy1300326388** [leanflutter/flutter_distributor#45]
- https://stackoverflow.com/questions/11888122/how-to-upload-an-ios-app-to-the-app-store-via-command-line
- https://progrunning.net/how-to-upload-ipa-app-package-to-apple-store-connect/
- https://memo.ecp.plus/upload_ipa/

**Comment by yy1300326388** [comment]
:pencil: `Doing`

**Comment by yy1300326388** [comment]
- https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api
- https://help.apple.com/asc/appsaltool/
- https://help.apple.com/asc/appsaltool/#/apdATD1E53-D1E1A1303-D1E53A1126

**Comment by yy1300326388** [comment]
- [App 专用密码获取](https://support.apple.com/HT204397)
- [App Store Connect api](https://developer.apple.com/documentation/appstoreconnectapi)

**Comment by lijy91** [comment]
已支持，请更新到 0.1.8
