### ISSUE TITLE
ProcessException: No such file or directory

### ISSUE THREAD

**Issue by yy1300326388** [leanflutter/flutter_distributor#5]
## 执行
```
flutter_distributor publish --path /dist/1.8.0+314/app-1.8.0+314-android.apk --targets fir
```

## Error
```
Unhandled exception:
ProcessException: No such file or directory
  Command: apkanalyzer manifest print /dist/1.8.0+314/app-1.8.0+314-android.apk
#0      AppPackagePublisherFir.publish (package:app_package_publisher_fir/src/app_package_publisher_fir.dart:109:7)
<asynchronous suspension>
#1      FlutterAppPublisher.publish (package:flutter_app_publisher/src/flutter_app_publisher.dart:21:12)
<asynchronous suspension>
#2      FlutterDistributor.publish (package:flutter_distributor/src/flutter_distributor.dart:82:37)
```

**Comment by yy1300326388** [comment]
我发现可能是我的 `apkanalyzer` 没有配置到环境变量中就会出错

**Comment by yy1300326388** [comment]
需要将 `${ANDROID_HOME}/tools/bin` 添加到环境变量中即可，程序需要做处理，不然无法继续，可能会看不懂

**Comment by lijy91** [comment]
可能要参考一下 https://github.com/chenquincy/app-info-parser 不依赖任何工具来解析 apk 包会好一点

**Comment by yy1300326388** [comment]
> 可能要参考一下 https://github.com/chenquincy/app-info-parser 不依赖任何工具来解析 apk 包会好一点

初步感觉这种解析比较好一点

**Comment by lijy91** [comment]
已经改用 aapt 来解析 apk 包，默认情况下会从环境变量 ANDROID_HOME 来确保 aapt 的路径正确

**Comment by nzkn** [comment]
Hello! I am getting following error when trying to build for macos:
```
Successfully builded Directory: 'build/macos/Build/Products/Release'
Unhandled exception:
ProcessException: No such file or directory
  Command: 7z a dist/1.4.7/app-1.4.7+1.4.7-macos.zip ./build/macos/Build/Products/Release/*.app
```
Can you suggest what I am doing wrong, please?

**Comment by lijy91** [comment]
> Hello! I am getting following error when trying to build for macos:
> ```
> Successfully builded Directory: 'build/macos/Build/Products/Release'
> Unhandled exception:
> ProcessException: No such file or directory
>   Command: 7z a dist/1.4.7/app-1.4.7+1.4.7-macos.zip ./build/macos/Build/Products/Release/*.app
> ```
> Can you suggest what I am doing wrong, please?

You need install 7z

https://distributor.leanflutter.org/docs/makers/zip

**Comment by nzkn** [comment]
Thanks!
