### ISSUE TITLE
同时打包2个IPA，编译成功之后复制到dist出错

### ISSUE THREAD

**Issue by weiwill** [leanflutter/flutter_distributor#55]
distribute_options.yaml
<img width="582" alt="image" src="https://user-images.githubusercontent.com/3794090/160076274-bd9780aa-6511-4aaa-be36-6d20fb43fe37.png">
```
File ipaFile = appDirectory
        .listSync()
        .where((e) => e.path.endsWith('.$packageFormat'))
        .map((e) => File(e.path))
        .first;
```
这里的代码目前只取第一个
<img width="212" alt="image" src="https://user-images.githubusercontent.com/3794090/160076551-3823bebd-cd0a-4e5d-a89a-8d0fb29ffd2c.png">

iOS和Android都有同样的问题

**Comment by yy1300326388** [comment]
确实有这个问题存在

**Comment by yy1300326388** [comment]
可以按添加文件时间排个序，然后取第一个，最新的在最前面，这样就不会出错了

**Comment by lijy91** [comment]
已修复，请更新到 0.2.0
