### ISSUE TITLE
Support Google Play publisher

### ISSUE THREAD

**Issue by davidmigloz** [leanflutter/flutter_distributor#62]
It would be great to support publishing apps to Google Play.

A good reference can be the https://github.com/Triple-T/gradle-play-publisher Gradle plugin.

**Comment by lijy91** [comment]
I'm almost done, the next version will be released

**Comment by yy1300326388** [comment]
目前有发布的计划吗？

**Comment by lijy91** [comment]
> 目前有发布的计划吗？

这个周未应该会发一个新版本

**Comment by jimmyleeking** [comment]
> I'm almost done, the next version will be released

so excited to hear about this message. it's so good tool for the developer!

**Comment by cybrox** [comment]
I see this has been added once but I cannot find it in the current sources/docs.

What is the current status of this?

**Comment by lijy91** [comment]
I just committed the code to , but I may need some time to test and polish it.
https://github.com/leanflutter/flutter_distributor/commit/02f1b112f626cb6a6d4ac535ff86c4ec00ef3f81

**Comment by lijy91** [comment]
Supported

**Comment by xcc3641** [comment]
Can you add to the documentation for Google Play?
