### ISSUE TITLE
New options to let chose install folder

### ISSUE THREAD

**Issue by Ros4111** [leanflutter/flutter_distributor#67]
Hello:
Flutter_distributor use Inno Setup to package the .exe installer for windows. This app let the user choose a some setting like:
DefaultDirName (now the app is installed in a c:\program files (x86)\    using the {autopf}   variable      I would like {sd} that is C: or D:
DisableDirPage     I would like to let the user choose the destiny directory (now it is not possible)

Setting (AppVersion and AppName) are in the file distribute_options.yaml and should be easy to add this options.

Thanks for your work.

**Comment by lijy91** [comment]
v0.2.5 已包含该改进
