### ISSUE TITLE
Could not find bin\flutter_distributor.dart in package flutter_distributor

### ISSUE THREAD

**Issue by EliasDeuss** [leanflutter/flutter_distributor#70]
I get this error: 
```Could not find bin\flutter_distributor.dart in package flutter_distributor. pub finished with exit code 66``` 

When trying to run:
```flutter pub run flutter_distributor release --name dev --jobs release-windows```

**Comment by lijy91** [comment]
Please call `flutter_distributor release --name dev --jobs release-windows` directly

**Comment by kjxbyz** [comment]
Running `dart run flutter_distributor:main`. It works for me.
