### ISSUE TITLE
fvm not support

### ISSUE THREAD

**Issue by ShellPeng** [leanflutter/flutter_distributor#77]
I have trouble in packaging zip for macos when i use fvm . for flutter，i have local version 2.8.1 and fvm version .

**Comment by nzkn** [comment]
The same issue for me

**Comment by Adherentman** [comment]
The same issue for me

**Comment by lijy91** [comment]
For fvm , you can add the fvm default version path to your .bashrc or .zshrc .

```
export PATH="$HOME/fvm/default/bin:$PATH"
```

You can use the flutter global command to switch versions.

```
fvm global 3.0.1
```
Or

```
fvm global 3.0.5
```
