### ISSUE TITLE
当build-tootls目录下存在.DS_Store文件时，执行命令会找错aapt命令路径

### ISSUE THREAD

**Issue by hiperioncn** [leanflutter/flutter_distributor#83]
按照文档例子编写的yaml，执行 flutter_distributor release --name dev后报错
<img width="1075" alt="66" src="https://user-images.githubusercontent.com/6045710/177900672-ac8e1a5d-1569-4dca-a87b-a032f817d114.png">
查找源码后发现，获取路径时使用的.first，所以获取的路径时错误的。
<img width="628" alt="image" src="https://user-images.githubusercontent.com/6045710/177900790-7d939928-d0eb-42c5-a950-48fdb073e318.png">
开始我在finder下确认目录下并没有.DS_Store文件，但在终端下却可以看到ls -l -a却可以看到该文件，先删除再说吧。

**Comment by yy1300326388** [comment]
这里默认去了first path 确实会有这样的问题，后续会优化处理

**Comment by lijy91** [comment]
已被 PR https://github.com/leanflutter/flutter_distributor/pull/84/files 修复
