### ISSUE TITLE
Unhandled exception: FileSystemException: Directory listing failed, path = 'build/ios/ipa/' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by superAndroidMan** [leanflutter/flutter_distributor#90]
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/26271318/187637105-f6b68b9c-052b-4f6f-80cc-f412ff2b3556.png">

Android能正常打包，iOS报错

**Comment by lijy91** [comment]
请先确保 flutter build ipa 能够正常执行
