### ISSUE TITLE
【蒲公英】升级到最新的 v2 接口，原来的 v2 接口即将废弃

### ISSUE THREAD

**Issue by yy1300326388** [leanflutter/flutter_distributor#91]
## 背景
近期收到了蒲公英团队的邮件如下，提醒我们升级到最新的 v2 API，之前的 v2 API 即将废弃
<img width="600" alt="image" src="https://user-images.githubusercontent.com/8764899/188319748-8d436154-bf47-46bc-92f3-4f6081e766f1.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/8764899/188319794-ee138839-ee35-40fe-9123-f7dbbeda2fbf.png">

## 升级

将参考 https://www.pgyer.com/doc/view/api#fastUploadApp 分为如下 3 不来完成上传发布
- 1、获取上传的 token
- 2、上传文件到第上一步获取的 URL
- 3、检测应用是否发布完成，并获取发布应用的信息

**Comment by yy1300326388** [comment]
@lijy91 分配给我吧

**Comment by yy1300326388** [comment]
参考链接： https://github.com/PGYER/pgyer_api_example/blob/main/nodejs-demo/PGYERAppUploader.js

**Comment by yy1300326388** [comment]
已完成开发，亲测新版本上传速度非常快
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/8764899/189057347-6b93a77d-036c-4952-82fb-d00cae7b0d1a.png">

**Comment by lijy91** [comment]
请更新到 v0.2.5
