### ISSUE TITLE
build a deb:  FileSystemException: Cannot open file, path = 'linux/packaging/deb/make_config.yaml

### ISSUE THREAD

**Issue by bksubhuti** [leanflutter/flutter_distributor#95]
I followed the instructions .. it built but gave this error`

`FileSystemException: Cannot open file, path = 'linux/packaging/deb/make_config.yaml`

I do not see any documentation for this.
I copied the file from the big example yaml

      - name: linux-deb
        package:
          platform: linux
          target: deb
          build_args:
            dart-define:
              APP_ENV: dev

**Comment by Auties00** [comment]
> I followed the instructions .. it built but gave this error`
> 
> `FileSystemException: Cannot open file, path = 'linux/packaging/deb/make_config.yaml`
> 
> I do not see any documentation for this. I copied the file from the big example yaml
> 
> ```
>   - name: linux-deb
>     package:
>       platform: linux
>       target: deb
>       build_args:
>         dart-define:
>           APP_ENV: dev
> ```

create  a file where it asks it to be and add something like:
```
app_id: someRandomId
publisher_name: SomeName
display_name: SomeDisplayName
create_desktop_icon: true
locales:
  - en
 ```

**Comment by lijy91** [comment]
Please add this make_config.yaml first.
