### ISSUE TITLE
打完安卓的包后直接结束了  RELEASE FAILED in 197s

### ISSUE THREAD

**Issue by zhangyu-1993** [leanflutter/flutter_distributor#96]
Successfully built Directory: 'build/app/outputs/flutter-apk' in 185s
Successfully packaged dist/1.0.8+63/outdoorsensor-arm64-1.0.8+63-android.apk

RELEASE FAILED in 197s

**Comment by zhangyu-1993** [comment]
补充一下版本信息 Flutter 2.8.1 • channel stable

**Comment by lijy91** [comment]
请更新到 0.3.0 后重试，看看输出的错误信息
